# Generated by Django 2.0.4 on 2018-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SALON', 'Salon'), ('CONFERENCE', 'Conference'), ('WORKSHOP', 'Workshop'), ('NETWORKING', 'Networking'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('banner_image_file', models.ImageField(upload_to='events/images/')),
                ('run_sheet', models.FileField(upload_to='events/runsheets/')),
                ('notes', models.TextField(blank=True, help_text='internal use only')),
            ],
        ),
    ]
