# Generated by Django 2.0.4 on 2018-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image_file',
            field=models.ImageField(blank=True, upload_to='events/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='run_sheet',
            field=models.FileField(blank=True, upload_to='events/runsheets/'),
        ),
    ]
