# Generated by Django 2.0.4 on 2018-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180415_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image_file',
            field=models.URLField(blank=True, help_text='link to the banner image file'),
        ),
        migrations.AlterField(
            model_name='event',
            name='run_sheet',
            field=models.URLField(blank=True, help_text='link to the runsheet document'),
        ),
    ]
