# Generated by Django 2.0.4 on 2018-04-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180415_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='banner_image_file',
            new_name='banner_image',
        ),
    ]
