# Generated by Django 2.0.4 on 2018-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180415_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='run_sheet',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True),
        ),
    ]
