# Generated by Django 2.0.4 on 2018-05-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedxuwa_user', '0004_auto_20180503_2045'),
        ('events', '0006_auto_20180503_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tedxuwa_user.Member')),
            ],
        ),
    ]
