# Generated by Django 2.0.4 on 2018-05-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedxuwa_user', '0005_auto_20180510_1126'),
        ('events', '0009_event_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='how many tickets did they buy')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tedxuwa_user.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='member',
        ),
        migrations.DeleteModel(
            name='EventSignup',
        ),
    ]
