# Generated by Django 2.0.4 on 2018-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180517_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='booking_method',
            field=models.CharField(blank=True, default='', help_text='how the person purchased the ticket', max_length=255),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='whether or not they actually checked into the event'),
        ),
    ]
