# Generated by Django 2.1.2 on 2018-10-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_speaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='event',
            new_name='events',
        ),
    ]
