# Generated by Django 2.1.2 on 2018-10-22 05:52

from django.db import migrations, models


def forward(apps, schema_editor):
    # set tag_line = bio
    Speaker = apps.get_model("events", "Speaker")
    for s in Speaker.objects.all():
        s.tag_line = s.bio
        s.save()


def backward(apps, schema_editor):
    # set empty tag_line
    Speaker = apps.get_model("events", "Speaker")
    Speaker.objects.all().update(tag_line="")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20181020_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='tag_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(forward, backward)
    ]
