# Generated by Django 2.1.7 on 2019-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_speaker_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, help_text='whether or not the event should be shown online'),
        ),
    ]
