# Generated by Django 2.0.4 on 2018-04-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedxuwa_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('profile_picutre_url', models.URLField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True, help_text='whether or not this member is a current comittee member')),
            ],
        ),
    ]
