# Generated by Django 2.0.4 on 2018-04-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tedxuwa_user', '0002_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='profile_picutre_url',
            new_name='profile_picture_url',
        ),
    ]
