# Generated by Django 2.0.4 on 2018-05-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedxuwa_user', '0004_auto_20180503_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_comittee',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='tedxuwa_user.Member'),
        ),
    ]
