# Generated by Django 2.0.4 on 2018-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedxuwa_user', '0005_auto_20180510_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='committeemember',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
