# Generated by Django 2.1.7 on 2019-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='benefits',
            field=models.CharField(choices=[('LDL', 'logo + description + link'), ('LD', 'logo + description'), ('L', 'logo')], default='L', max_length=3),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
