# Generated by Django 2.1.7 on 2019-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190416_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='benefits',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.IntegerField(default=3, help_text='3 is the lowest and 1 is the highest'),
        ),
    ]
