# Generated by Django 2.1.7 on 2019-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190416_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.IntegerField(default=3, help_text='3 is the lowest and 1 is the highest where 3 = logo+description+link, 2 = logo+description and 1 = logo'),
        ),
    ]
