# Generated by Django 2.2.4 on 2019-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190416_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of the webpage, this will be shown on link previews', max_length=255)),
                ('path', models.SlugField(help_text='the path for this url. The end result will be tedxuwa.com/r/PATH', max_length=255, unique=True)),
                ('link', models.URLField(help_text='the link that this path leads to')),
            ],
        ),
    ]
